# Generated by Django 4.0.1 on 2022-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_cashindelivery_product_image_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_no',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
