# Generated by Django 4.0.1 on 2022-01-25 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_rename_cashindelivery_order_cashondelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=14, null=True)),
                ('shop_name', models.CharField(max_length=244, null=True)),
                ('shop_address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('shiop_area_code', models.CharField(blank=True, max_length=2, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=9, null=True)),
                ('image', models.ImageField(blank=True, default='/profilepic.png', null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ShopCreate',
        ),
    ]
