# Generated by Django 4.0.1 on 2022-01-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_profilecreate_delete_shopcreate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
