# Generated by Django 4.0.1 on 2022-01-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone_no',
        ),
    ]
